#ifndef PROJECTN_FOREACH_H
#define PROJECTN_FOREACH_H
#pragma once


 
#define EXPAND(x) x
#define FOREACH_1(what, x) what(x)
#define FOREACH_2(what, x, ...) what(x) EXPAND(FOREACH_1(what, __VA_ARGS__))
#define FOREACH_3(what, x, ...) what(x) EXPAND(FOREACH_2(what, __VA_ARGS__))
#define FOREACH_4(what, x, ...) what(x) EXPAND(FOREACH_3(what, __VA_ARGS__))
#define FOREACH_5(what, x, ...) what(x) EXPAND(FOREACH_4(what, __VA_ARGS__))
#define FOREACH_6(what, x, ...) what(x) EXPAND(FOREACH_5(what, __VA_ARGS__))
#define FOREACH_7(what, x, ...) what(x) EXPAND(FOREACH_6(what, __VA_ARGS__))
#define FOREACH_8(what, x, ...) what(x) EXPAND(FOREACH_7(what, __VA_ARGS__))
#define FOREACH_9(what, x, ...) what(x) EXPAND(FOREACH_8(what, __VA_ARGS__))
#define FOREACH_10(what, x, ...) what(x) EXPAND(FOREACH_9(what, __VA_ARGS__))
#define FOREACH_11(what, x, ...) what(x) EXPAND(FOREACH_10(what, __VA_ARGS__))
#define FOREACH_12(what, x, ...) what(x) EXPAND(FOREACH_11(what, __VA_ARGS__))
#define FOREACH_13(what, x, ...) what(x) EXPAND(FOREACH_12(what, __VA_ARGS__))
#define FOREACH_14(what, x, ...) what(x) EXPAND(FOREACH_13(what, __VA_ARGS__))
#define FOREACH_15(what, x, ...) what(x) EXPAND(FOREACH_14(what, __VA_ARGS__))
#define FOREACH_16(what, x, ...) what(x) EXPAND(FOREACH_15(what, __VA_ARGS__))
#define FOREACH_17(what, x, ...) what(x) EXPAND(FOREACH_16(what, __VA_ARGS__))
#define FOREACH_18(what, x, ...) what(x) EXPAND(FOREACH_17(what, __VA_ARGS__))
#define FOREACH_19(what, x, ...) what(x) EXPAND(FOREACH_18(what, __VA_ARGS__))
#define FOREACH_20(what, x, ...) what(x) EXPAND(FOREACH_19(what, __VA_ARGS__))
#define FOREACH_21(what, x, ...) what(x) EXPAND(FOREACH_20(what, __VA_ARGS__))
#define FOREACH_22(what, x, ...) what(x) EXPAND(FOREACH_21(what, __VA_ARGS__))
#define FOREACH_23(what, x, ...) what(x) EXPAND(FOREACH_22(what, __VA_ARGS__))
#define FOREACH_24(what, x, ...) what(x) EXPAND(FOREACH_23(what, __VA_ARGS__))
#define FOREACH_25(what, x, ...) what(x) EXPAND(FOREACH_24(what, __VA_ARGS__))
#define FOREACH_26(what, x, ...) what(x) EXPAND(FOREACH_25(what, __VA_ARGS__))
#define FOREACH_27(what, x, ...) what(x) EXPAND(FOREACH_26(what, __VA_ARGS__))
#define FOREACH_28(what, x, ...) what(x) EXPAND(FOREACH_27(what, __VA_ARGS__))
#define FOREACH_29(what, x, ...) what(x) EXPAND(FOREACH_28(what, __VA_ARGS__))
#define FOREACH_30(what, x, ...) what(x) EXPAND(FOREACH_29(what, __VA_ARGS__))
#define FOREACH_31(what, x, ...) what(x) EXPAND(FOREACH_30(what, __VA_ARGS__))
#define FOREACH_32(what, x, ...) what(x) EXPAND(FOREACH_31(what, __VA_ARGS__))
#define FOREACH_33(what, x, ...) what(x) EXPAND(FOREACH_32(what, __VA_ARGS__))
#define FOREACH_34(what, x, ...) what(x) EXPAND(FOREACH_33(what, __VA_ARGS__))
#define FOREACH_35(what, x, ...) what(x) EXPAND(FOREACH_34(what, __VA_ARGS__))
#define FOREACH_36(what, x, ...) what(x) EXPAND(FOREACH_35(what, __VA_ARGS__))
#define FOREACH_37(what, x, ...) what(x) EXPAND(FOREACH_36(what, __VA_ARGS__))
#define FOREACH_38(what, x, ...) what(x) EXPAND(FOREACH_37(what, __VA_ARGS__))
#define FOREACH_39(what, x, ...) what(x) EXPAND(FOREACH_38(what, __VA_ARGS__))
#define FOREACH_40(what, x, ...) what(x) EXPAND(FOREACH_39(what, __VA_ARGS__))
#define FOREACH_41(what, x, ...) what(x) EXPAND(FOREACH_40(what, __VA_ARGS__))
#define FOREACH_42(what, x, ...) what(x) EXPAND(FOREACH_41(what, __VA_ARGS__))
#define FOREACH_43(what, x, ...) what(x) EXPAND(FOREACH_42(what, __VA_ARGS__))
#define FOREACH_44(what, x, ...) what(x) EXPAND(FOREACH_43(what, __VA_ARGS__))
#define FOREACH_45(what, x, ...) what(x) EXPAND(FOREACH_44(what, __VA_ARGS__))
#define FOREACH_46(what, x, ...) what(x) EXPAND(FOREACH_45(what, __VA_ARGS__))
#define FOREACH_47(what, x, ...) what(x) EXPAND(FOREACH_46(what, __VA_ARGS__))
#define FOREACH_48(what, x, ...) what(x) EXPAND(FOREACH_47(what, __VA_ARGS__))
#define FOREACH_49(what, x, ...) what(x) EXPAND(FOREACH_48(what, __VA_ARGS__))
#define FOREACH_50(what, x, ...) what(x) EXPAND(FOREACH_49(what, __VA_ARGS__))
#define FOREACH_51(what, x, ...) what(x) EXPAND(FOREACH_50(what, __VA_ARGS__))
#define FOREACH_52(what, x, ...) what(x) EXPAND(FOREACH_51(what, __VA_ARGS__))
#define FOREACH_53(what, x, ...) what(x) EXPAND(FOREACH_52(what, __VA_ARGS__))
#define FOREACH_54(what, x, ...) what(x) EXPAND(FOREACH_53(what, __VA_ARGS__))
#define FOREACH_55(what, x, ...) what(x) EXPAND(FOREACH_54(what, __VA_ARGS__))
#define FOREACH_56(what, x, ...) what(x) EXPAND(FOREACH_55(what, __VA_ARGS__))
#define FOREACH_57(what, x, ...) what(x) EXPAND(FOREACH_56(what, __VA_ARGS__))
#define FOREACH_58(what, x, ...) what(x) EXPAND(FOREACH_57(what, __VA_ARGS__))
#define FOREACH_59(what, x, ...) what(x) EXPAND(FOREACH_58(what, __VA_ARGS__))
#define FOREACH_60(what, x, ...) what(x) EXPAND(FOREACH_59(what, __VA_ARGS__))
#define FOREACH_61(what, x, ...) what(x) EXPAND(FOREACH_60(what, __VA_ARGS__))
#define FOREACH_62(what, x, ...) what(x) EXPAND(FOREACH_61(what, __VA_ARGS__))
#define FOREACH_63(what, x, ...) what(x) EXPAND(FOREACH_62(what, __VA_ARGS__))
#define FOREACH_64(what, x, ...) what(x) EXPAND(FOREACH_63(what, __VA_ARGS__))
#define FOREACH_65(what, x, ...) what(x) EXPAND(FOREACH_64(what, __VA_ARGS__))
#define FOREACH_66(what, x, ...) what(x) EXPAND(FOREACH_65(what, __VA_ARGS__))
#define FOREACH_67(what, x, ...) what(x) EXPAND(FOREACH_66(what, __VA_ARGS__))
#define FOREACH_68(what, x, ...) what(x) EXPAND(FOREACH_67(what, __VA_ARGS__))
#define FOREACH_69(what, x, ...) what(x) EXPAND(FOREACH_68(what, __VA_ARGS__))
#define FOREACH_70(what, x, ...) what(x) EXPAND(FOREACH_69(what, __VA_ARGS__))
#define FOREACH_71(what, x, ...) what(x) EXPAND(FOREACH_70(what, __VA_ARGS__))
#define FOREACH_72(what, x, ...) what(x) EXPAND(FOREACH_71(what, __VA_ARGS__))
#define FOREACH_73(what, x, ...) what(x) EXPAND(FOREACH_72(what, __VA_ARGS__))
#define FOREACH_74(what, x, ...) what(x) EXPAND(FOREACH_73(what, __VA_ARGS__))
#define FOREACH_75(what, x, ...) what(x) EXPAND(FOREACH_74(what, __VA_ARGS__))
#define FOREACH_76(what, x, ...) what(x) EXPAND(FOREACH_75(what, __VA_ARGS__))
#define FOREACH_77(what, x, ...) what(x) EXPAND(FOREACH_76(what, __VA_ARGS__))
#define FOREACH_78(what, x, ...) what(x) EXPAND(FOREACH_77(what, __VA_ARGS__))
#define FOREACH_79(what, x, ...) what(x) EXPAND(FOREACH_78(what, __VA_ARGS__))
#define FOREACH_80(what, x, ...) what(x) EXPAND(FOREACH_79(what, __VA_ARGS__))
#define FOREACH_81(what, x, ...) what(x) EXPAND(FOREACH_80(what, __VA_ARGS__))
#define FOREACH_82(what, x, ...) what(x) EXPAND(FOREACH_81(what, __VA_ARGS__))
#define FOREACH_83(what, x, ...) what(x) EXPAND(FOREACH_82(what, __VA_ARGS__))
#define FOREACH_84(what, x, ...) what(x) EXPAND(FOREACH_83(what, __VA_ARGS__))
#define FOREACH_85(what, x, ...) what(x) EXPAND(FOREACH_84(what, __VA_ARGS__))
#define FOREACH_86(what, x, ...) what(x) EXPAND(FOREACH_85(what, __VA_ARGS__))
#define FOREACH_87(what, x, ...) what(x) EXPAND(FOREACH_86(what, __VA_ARGS__))
#define FOREACH_88(what, x, ...) what(x) EXPAND(FOREACH_87(what, __VA_ARGS__))
#define FOREACH_89(what, x, ...) what(x) EXPAND(FOREACH_88(what, __VA_ARGS__))
#define FOREACH_90(what, x, ...) what(x) EXPAND(FOREACH_89(what, __VA_ARGS__))
#define FOREACH_91(what, x, ...) what(x) EXPAND(FOREACH_90(what, __VA_ARGS__))
#define FOREACH_92(what, x, ...) what(x) EXPAND(FOREACH_91(what, __VA_ARGS__))
#define FOREACH_93(what, x, ...) what(x) EXPAND(FOREACH_92(what, __VA_ARGS__))
#define FOREACH_94(what, x, ...) what(x) EXPAND(FOREACH_93(what, __VA_ARGS__))
#define FOREACH_95(what, x, ...) what(x) EXPAND(FOREACH_94(what, __VA_ARGS__))
#define FOREACH_96(what, x, ...) what(x) EXPAND(FOREACH_95(what, __VA_ARGS__))
#define FOREACH_97(what, x, ...) what(x) EXPAND(FOREACH_96(what, __VA_ARGS__))
#define FOREACH_98(what, x, ...) what(x) EXPAND(FOREACH_97(what, __VA_ARGS__))
#define FOREACH_99(what, x, ...) what(x) EXPAND(FOREACH_98(what, __VA_ARGS__))



#define FOREACH2_1(what, x, y) what(x, y)
#define FOREACH2_2(what, x, y, ...) what(x, y) EXPAND(FOREACH2_1(what, __VA_ARGS__))
#define FOREACH2_3(what, x, y, ...) what(x, y) EXPAND(FOREACH2_2(what, __VA_ARGS__))
#define FOREACH2_4(what, x, y, ...) what(x, y) EXPAND(FOREACH2_3(what, __VA_ARGS__))
#define FOREACH2_5(what, x, y, ...) what(x, y) EXPAND(FOREACH2_4(what, __VA_ARGS__))
#define FOREACH2_6(what, x, y, ...) what(x, y) EXPAND(FOREACH2_5(what, __VA_ARGS__))
#define FOREACH2_7(what, x, y, ...) what(x, y) EXPAND(FOREACH2_6(what, __VA_ARGS__))
#define FOREACH2_8(what, x, y, ...) what(x, y) EXPAND(FOREACH2_7(what, __VA_ARGS__))
#define FOREACH2_9(what, x, y, ...) what(x, y) EXPAND(FOREACH2_8(what, __VA_ARGS__))
#define FOREACH2_10(what, x, y, ...) what(x, y) EXPAND(FOREACH2_9(what, __VA_ARGS__))
#define FOREACH2_11(what, x, y, ...) what(x, y) EXPAND(FOREACH2_10(what, __VA_ARGS__))
#define FOREACH2_12(what, x, y, ...) what(x, y) EXPAND(FOREACH2_11(what, __VA_ARGS__))
#define FOREACH2_13(what, x, y, ...) what(x, y) EXPAND(FOREACH2_12(what, __VA_ARGS__))
#define FOREACH2_14(what, x, y, ...) what(x, y) EXPAND(FOREACH2_13(what, __VA_ARGS__))
#define FOREACH2_15(what, x, y, ...) what(x, y) EXPAND(FOREACH2_14(what, __VA_ARGS__))
#define FOREACH2_16(what, x, y, ...) what(x, y) EXPAND(FOREACH2_15(what, __VA_ARGS__))
#define FOREACH2_17(what, x, y, ...) what(x, y) EXPAND(FOREACH2_16(what, __VA_ARGS__))
#define FOREACH2_18(what, x, y, ...) what(x, y) EXPAND(FOREACH2_17(what, __VA_ARGS__))
#define FOREACH2_19(what, x, y, ...) what(x, y) EXPAND(FOREACH2_18(what, __VA_ARGS__))
#define FOREACH2_20(what, x, y, ...) what(x, y) EXPAND(FOREACH2_19(what, __VA_ARGS__))
#define FOREACH2_21(what, x, y, ...) what(x, y) EXPAND(FOREACH2_20(what, __VA_ARGS__))
#define FOREACH2_22(what, x, y, ...) what(x, y) EXPAND(FOREACH2_21(what, __VA_ARGS__))
#define FOREACH2_23(what, x, y, ...) what(x, y) EXPAND(FOREACH2_22(what, __VA_ARGS__))
#define FOREACH2_24(what, x, y, ...) what(x, y) EXPAND(FOREACH2_23(what, __VA_ARGS__))
#define FOREACH2_25(what, x, y, ...) what(x, y) EXPAND(FOREACH2_24(what, __VA_ARGS__))
#define FOREACH2_26(what, x, y, ...) what(x, y) EXPAND(FOREACH2_25(what, __VA_ARGS__))
#define FOREACH2_27(what, x, y, ...) what(x, y) EXPAND(FOREACH2_26(what, __VA_ARGS__))
#define FOREACH2_28(what, x, y, ...) what(x, y) EXPAND(FOREACH2_27(what, __VA_ARGS__))
#define FOREACH2_29(what, x, y, ...) what(x, y) EXPAND(FOREACH2_28(what, __VA_ARGS__))
#define FOREACH2_30(what, x, y, ...) what(x, y) EXPAND(FOREACH2_29(what, __VA_ARGS__))
#define FOREACH2_31(what, x, y, ...) what(x, y) EXPAND(FOREACH2_30(what, __VA_ARGS__))
#define FOREACH2_32(what, x, y, ...) what(x, y) EXPAND(FOREACH2_31(what, __VA_ARGS__))
#define FOREACH2_33(what, x, y, ...) what(x, y) EXPAND(FOREACH2_32(what, __VA_ARGS__))
#define FOREACH2_34(what, x, y, ...) what(x, y) EXPAND(FOREACH2_33(what, __VA_ARGS__))
#define FOREACH2_35(what, x, y, ...) what(x, y) EXPAND(FOREACH2_34(what, __VA_ARGS__))
#define FOREACH2_36(what, x, y, ...) what(x, y) EXPAND(FOREACH2_35(what, __VA_ARGS__))
#define FOREACH2_37(what, x, y, ...) what(x, y) EXPAND(FOREACH2_36(what, __VA_ARGS__))
#define FOREACH2_38(what, x, y, ...) what(x, y) EXPAND(FOREACH2_37(what, __VA_ARGS__))
#define FOREACH2_39(what, x, y, ...) what(x, y) EXPAND(FOREACH2_38(what, __VA_ARGS__))
#define FOREACH2_40(what, x, y, ...) what(x, y) EXPAND(FOREACH2_39(what, __VA_ARGS__))
#define FOREACH2_41(what, x, y, ...) what(x, y) EXPAND(FOREACH2_40(what, __VA_ARGS__))
#define FOREACH2_42(what, x, y, ...) what(x, y) EXPAND(FOREACH2_41(what, __VA_ARGS__))
#define FOREACH2_43(what, x, y, ...) what(x, y) EXPAND(FOREACH2_42(what, __VA_ARGS__))
#define FOREACH2_44(what, x, y, ...) what(x, y) EXPAND(FOREACH2_43(what, __VA_ARGS__))
#define FOREACH2_45(what, x, y, ...) what(x, y) EXPAND(FOREACH2_44(what, __VA_ARGS__))
#define FOREACH2_46(what, x, y, ...) what(x, y) EXPAND(FOREACH2_45(what, __VA_ARGS__))
#define FOREACH2_47(what, x, y, ...) what(x, y) EXPAND(FOREACH2_46(what, __VA_ARGS__))
#define FOREACH2_48(what, x, y, ...) what(x, y) EXPAND(FOREACH2_47(what, __VA_ARGS__))
#define FOREACH2_49(what, x, y, ...) what(x, y) EXPAND(FOREACH2_48(what, __VA_ARGS__))
#define FOREACH2_50(what, x, y, ...) what(x, y) EXPAND(FOREACH2_49(what, __VA_ARGS__))
#define FOREACH2_51(what, x, y, ...) what(x, y) EXPAND(FOREACH2_50(what, __VA_ARGS__))
#define FOREACH2_52(what, x, y, ...) what(x, y) EXPAND(FOREACH2_51(what, __VA_ARGS__))
#define FOREACH2_53(what, x, y, ...) what(x, y) EXPAND(FOREACH2_52(what, __VA_ARGS__))
#define FOREACH2_54(what, x, y, ...) what(x, y) EXPAND(FOREACH2_53(what, __VA_ARGS__))
#define FOREACH2_55(what, x, y, ...) what(x, y) EXPAND(FOREACH2_54(what, __VA_ARGS__))
#define FOREACH2_56(what, x, y, ...) what(x, y) EXPAND(FOREACH2_55(what, __VA_ARGS__))
#define FOREACH2_57(what, x, y, ...) what(x, y) EXPAND(FOREACH2_56(what, __VA_ARGS__))
#define FOREACH2_58(what, x, y, ...) what(x, y) EXPAND(FOREACH2_57(what, __VA_ARGS__))
#define FOREACH2_59(what, x, y, ...) what(x, y) EXPAND(FOREACH2_58(what, __VA_ARGS__))
#define FOREACH2_60(what, x, y, ...) what(x, y) EXPAND(FOREACH2_59(what, __VA_ARGS__))
#define FOREACH2_61(what, x, y, ...) what(x, y) EXPAND(FOREACH2_60(what, __VA_ARGS__))
#define FOREACH2_62(what, x, y, ...) what(x, y) EXPAND(FOREACH2_61(what, __VA_ARGS__))
#define FOREACH2_63(what, x, y, ...) what(x, y) EXPAND(FOREACH2_62(what, __VA_ARGS__))
#define FOREACH2_64(what, x, y, ...) what(x, y) EXPAND(FOREACH2_63(what, __VA_ARGS__))
#define FOREACH2_65(what, x, y, ...) what(x, y) EXPAND(FOREACH2_64(what, __VA_ARGS__))
#define FOREACH2_66(what, x, y, ...) what(x, y) EXPAND(FOREACH2_65(what, __VA_ARGS__))
#define FOREACH2_67(what, x, y, ...) what(x, y) EXPAND(FOREACH2_66(what, __VA_ARGS__))
#define FOREACH2_68(what, x, y, ...) what(x, y) EXPAND(FOREACH2_67(what, __VA_ARGS__))
#define FOREACH2_69(what, x, y, ...) what(x, y) EXPAND(FOREACH2_68(what, __VA_ARGS__))
#define FOREACH2_70(what, x, y, ...) what(x, y) EXPAND(FOREACH2_69(what, __VA_ARGS__))
#define FOREACH2_71(what, x, y, ...) what(x, y) EXPAND(FOREACH2_70(what, __VA_ARGS__))
#define FOREACH2_72(what, x, y, ...) what(x, y) EXPAND(FOREACH2_71(what, __VA_ARGS__))
#define FOREACH2_73(what, x, y, ...) what(x, y) EXPAND(FOREACH2_72(what, __VA_ARGS__))
#define FOREACH2_74(what, x, y, ...) what(x, y) EXPAND(FOREACH2_73(what, __VA_ARGS__))
#define FOREACH2_75(what, x, y, ...) what(x, y) EXPAND(FOREACH2_74(what, __VA_ARGS__))
#define FOREACH2_76(what, x, y, ...) what(x, y) EXPAND(FOREACH2_75(what, __VA_ARGS__))
#define FOREACH2_77(what, x, y, ...) what(x, y) EXPAND(FOREACH2_76(what, __VA_ARGS__))
#define FOREACH2_78(what, x, y, ...) what(x, y) EXPAND(FOREACH2_77(what, __VA_ARGS__))
#define FOREACH2_79(what, x, y, ...) what(x, y) EXPAND(FOREACH2_78(what, __VA_ARGS__))
#define FOREACH2_80(what, x, y, ...) what(x, y) EXPAND(FOREACH2_79(what, __VA_ARGS__))
#define FOREACH2_81(what, x, y, ...) what(x, y) EXPAND(FOREACH2_80(what, __VA_ARGS__))
#define FOREACH2_82(what, x, y, ...) what(x, y) EXPAND(FOREACH2_81(what, __VA_ARGS__))
#define FOREACH2_83(what, x, y, ...) what(x, y) EXPAND(FOREACH2_82(what, __VA_ARGS__))
#define FOREACH2_84(what, x, y, ...) what(x, y) EXPAND(FOREACH2_83(what, __VA_ARGS__))
#define FOREACH2_85(what, x, y, ...) what(x, y) EXPAND(FOREACH2_84(what, __VA_ARGS__))
#define FOREACH2_86(what, x, y, ...) what(x, y) EXPAND(FOREACH2_85(what, __VA_ARGS__))
#define FOREACH2_87(what, x, y, ...) what(x, y) EXPAND(FOREACH2_86(what, __VA_ARGS__))
#define FOREACH2_88(what, x, y, ...) what(x, y) EXPAND(FOREACH2_87(what, __VA_ARGS__))
#define FOREACH2_89(what, x, y, ...) what(x, y) EXPAND(FOREACH2_88(what, __VA_ARGS__))
#define FOREACH2_90(what, x, y, ...) what(x, y) EXPAND(FOREACH2_89(what, __VA_ARGS__))
#define FOREACH2_91(what, x, y, ...) what(x, y) EXPAND(FOREACH2_90(what, __VA_ARGS__))
#define FOREACH2_92(what, x, y, ...) what(x, y) EXPAND(FOREACH2_91(what, __VA_ARGS__))
#define FOREACH2_93(what, x, y, ...) what(x, y) EXPAND(FOREACH2_92(what, __VA_ARGS__))
#define FOREACH2_94(what, x, y, ...) what(x, y) EXPAND(FOREACH2_93(what, __VA_ARGS__))
#define FOREACH2_95(what, x, y, ...) what(x, y) EXPAND(FOREACH2_94(what, __VA_ARGS__))
#define FOREACH2_96(what, x, y, ...) what(x, y) EXPAND(FOREACH2_95(what, __VA_ARGS__))
#define FOREACH2_97(what, x, y, ...) what(x, y) EXPAND(FOREACH2_96(what, __VA_ARGS__))
#define FOREACH2_98(what, x, y, ...) what(x, y) EXPAND(FOREACH2_97(what, __VA_ARGS__))
#define FOREACH2_99(what, x, y, ...) what(x, y) EXPAND(FOREACH2_98(what, __VA_ARGS__))



#define FOREACH3_1(what, x, y) what(x, y)
#define FOREACH3_2(what, x, y, ...) what(x, y) EXPAND(FOREACH3_1(what, x, __VA_ARGS__))
#define FOREACH3_3(what, x, y, ...) what(x, y) EXPAND(FOREACH3_2(what, x, __VA_ARGS__))
#define FOREACH3_4(what, x, y, ...) what(x, y) EXPAND(FOREACH3_3(what, x, __VA_ARGS__))
#define FOREACH3_5(what, x, y, ...) what(x, y) EXPAND(FOREACH3_4(what, x, __VA_ARGS__))
#define FOREACH3_6(what, x, y, ...) what(x, y) EXPAND(FOREACH3_5(what, x, __VA_ARGS__))
#define FOREACH3_7(what, x, y, ...) what(x, y) EXPAND(FOREACH3_6(what, x, __VA_ARGS__))
#define FOREACH3_8(what, x, y, ...) what(x, y) EXPAND(FOREACH3_7(what, x, __VA_ARGS__))
#define FOREACH3_9(what, x, y, ...) what(x, y) EXPAND(FOREACH3_8(what, x, __VA_ARGS__))
#define FOREACH3_10(what, x, y, ...) what(x, y) EXPAND(FOREACH3_9(what, x, __VA_ARGS__))
#define FOREACH3_11(what, x, y, ...) what(x, y) EXPAND(FOREACH3_10(what, x, __VA_ARGS__))
#define FOREACH3_12(what, x, y, ...) what(x, y) EXPAND(FOREACH3_11(what, x, __VA_ARGS__))
#define FOREACH3_13(what, x, y, ...) what(x, y) EXPAND(FOREACH3_12(what, x, __VA_ARGS__))
#define FOREACH3_14(what, x, y, ...) what(x, y) EXPAND(FOREACH3_13(what, x, __VA_ARGS__))
#define FOREACH3_15(what, x, y, ...) what(x, y) EXPAND(FOREACH3_14(what, x, __VA_ARGS__))
#define FOREACH3_16(what, x, y, ...) what(x, y) EXPAND(FOREACH3_15(what, x, __VA_ARGS__))
#define FOREACH3_17(what, x, y, ...) what(x, y) EXPAND(FOREACH3_16(what, x, __VA_ARGS__))
#define FOREACH3_18(what, x, y, ...) what(x, y) EXPAND(FOREACH3_17(what, x, __VA_ARGS__))
#define FOREACH3_19(what, x, y, ...) what(x, y) EXPAND(FOREACH3_18(what, x, __VA_ARGS__))
#define FOREACH3_20(what, x, y, ...) what(x, y) EXPAND(FOREACH3_19(what, x, __VA_ARGS__))
#define FOREACH3_21(what, x, y, ...) what(x, y) EXPAND(FOREACH3_20(what, x, __VA_ARGS__))
#define FOREACH3_22(what, x, y, ...) what(x, y) EXPAND(FOREACH3_21(what, x, __VA_ARGS__))
#define FOREACH3_23(what, x, y, ...) what(x, y) EXPAND(FOREACH3_22(what, x, __VA_ARGS__))
#define FOREACH3_24(what, x, y, ...) what(x, y) EXPAND(FOREACH3_23(what, x, __VA_ARGS__))
#define FOREACH3_25(what, x, y, ...) what(x, y) EXPAND(FOREACH3_24(what, x, __VA_ARGS__))
#define FOREACH3_26(what, x, y, ...) what(x, y) EXPAND(FOREACH3_25(what, x, __VA_ARGS__))
#define FOREACH3_27(what, x, y, ...) what(x, y) EXPAND(FOREACH3_26(what, x, __VA_ARGS__))
#define FOREACH3_28(what, x, y, ...) what(x, y) EXPAND(FOREACH3_27(what, x, __VA_ARGS__))
#define FOREACH3_29(what, x, y, ...) what(x, y) EXPAND(FOREACH3_28(what, x, __VA_ARGS__))
#define FOREACH3_30(what, x, y, ...) what(x, y) EXPAND(FOREACH3_29(what, x, __VA_ARGS__))
#define FOREACH3_31(what, x, y, ...) what(x, y) EXPAND(FOREACH3_30(what, x, __VA_ARGS__))
#define FOREACH3_32(what, x, y, ...) what(x, y) EXPAND(FOREACH3_31(what, x, __VA_ARGS__))
#define FOREACH3_33(what, x, y, ...) what(x, y) EXPAND(FOREACH3_32(what, x, __VA_ARGS__))
#define FOREACH3_34(what, x, y, ...) what(x, y) EXPAND(FOREACH3_33(what, x, __VA_ARGS__))
#define FOREACH3_35(what, x, y, ...) what(x, y) EXPAND(FOREACH3_34(what, x, __VA_ARGS__))
#define FOREACH3_36(what, x, y, ...) what(x, y) EXPAND(FOREACH3_35(what, x, __VA_ARGS__))
#define FOREACH3_37(what, x, y, ...) what(x, y) EXPAND(FOREACH3_36(what, x, __VA_ARGS__))
#define FOREACH3_38(what, x, y, ...) what(x, y) EXPAND(FOREACH3_37(what, x, __VA_ARGS__))
#define FOREACH3_39(what, x, y, ...) what(x, y) EXPAND(FOREACH3_38(what, x, __VA_ARGS__))
#define FOREACH3_40(what, x, y, ...) what(x, y) EXPAND(FOREACH3_39(what, x, __VA_ARGS__))
#define FOREACH3_41(what, x, y, ...) what(x, y) EXPAND(FOREACH3_40(what, x, __VA_ARGS__))
#define FOREACH3_42(what, x, y, ...) what(x, y) EXPAND(FOREACH3_41(what, x, __VA_ARGS__))
#define FOREACH3_43(what, x, y, ...) what(x, y) EXPAND(FOREACH3_42(what, x, __VA_ARGS__))
#define FOREACH3_44(what, x, y, ...) what(x, y) EXPAND(FOREACH3_43(what, x, __VA_ARGS__))
#define FOREACH3_45(what, x, y, ...) what(x, y) EXPAND(FOREACH3_44(what, x, __VA_ARGS__))
#define FOREACH3_46(what, x, y, ...) what(x, y) EXPAND(FOREACH3_45(what, x, __VA_ARGS__))
#define FOREACH3_47(what, x, y, ...) what(x, y) EXPAND(FOREACH3_46(what, x, __VA_ARGS__))
#define FOREACH3_48(what, x, y, ...) what(x, y) EXPAND(FOREACH3_47(what, x, __VA_ARGS__))
#define FOREACH3_49(what, x, y, ...) what(x, y) EXPAND(FOREACH3_48(what, x, __VA_ARGS__))
#define FOREACH3_50(what, x, y, ...) what(x, y) EXPAND(FOREACH3_49(what, x, __VA_ARGS__))
#define FOREACH3_51(what, x, y, ...) what(x, y) EXPAND(FOREACH3_50(what, x, __VA_ARGS__))
#define FOREACH3_52(what, x, y, ...) what(x, y) EXPAND(FOREACH3_51(what, x, __VA_ARGS__))
#define FOREACH3_53(what, x, y, ...) what(x, y) EXPAND(FOREACH3_52(what, x, __VA_ARGS__))
#define FOREACH3_54(what, x, y, ...) what(x, y) EXPAND(FOREACH3_53(what, x, __VA_ARGS__))
#define FOREACH3_55(what, x, y, ...) what(x, y) EXPAND(FOREACH3_54(what, x, __VA_ARGS__))
#define FOREACH3_56(what, x, y, ...) what(x, y) EXPAND(FOREACH3_55(what, x, __VA_ARGS__))
#define FOREACH3_57(what, x, y, ...) what(x, y) EXPAND(FOREACH3_56(what, x, __VA_ARGS__))
#define FOREACH3_58(what, x, y, ...) what(x, y) EXPAND(FOREACH3_57(what, x, __VA_ARGS__))
#define FOREACH3_59(what, x, y, ...) what(x, y) EXPAND(FOREACH3_58(what, x, __VA_ARGS__))
#define FOREACH3_60(what, x, y, ...) what(x, y) EXPAND(FOREACH3_59(what, x, __VA_ARGS__))
#define FOREACH3_61(what, x, y, ...) what(x, y) EXPAND(FOREACH3_60(what, x, __VA_ARGS__))
#define FOREACH3_62(what, x, y, ...) what(x, y) EXPAND(FOREACH3_61(what, x, __VA_ARGS__))
#define FOREACH3_63(what, x, y, ...) what(x, y) EXPAND(FOREACH3_62(what, x, __VA_ARGS__))
#define FOREACH3_64(what, x, y, ...) what(x, y) EXPAND(FOREACH3_63(what, x, __VA_ARGS__))
#define FOREACH3_65(what, x, y, ...) what(x, y) EXPAND(FOREACH3_64(what, x, __VA_ARGS__))
#define FOREACH3_66(what, x, y, ...) what(x, y) EXPAND(FOREACH3_65(what, x, __VA_ARGS__))
#define FOREACH3_67(what, x, y, ...) what(x, y) EXPAND(FOREACH3_66(what, x, __VA_ARGS__))
#define FOREACH3_68(what, x, y, ...) what(x, y) EXPAND(FOREACH3_67(what, x, __VA_ARGS__))
#define FOREACH3_69(what, x, y, ...) what(x, y) EXPAND(FOREACH3_68(what, x, __VA_ARGS__))
#define FOREACH3_70(what, x, y, ...) what(x, y) EXPAND(FOREACH3_69(what, x, __VA_ARGS__))
#define FOREACH3_71(what, x, y, ...) what(x, y) EXPAND(FOREACH3_70(what, x, __VA_ARGS__))
#define FOREACH3_72(what, x, y, ...) what(x, y) EXPAND(FOREACH3_71(what, x, __VA_ARGS__))
#define FOREACH3_73(what, x, y, ...) what(x, y) EXPAND(FOREACH3_72(what, x, __VA_ARGS__))
#define FOREACH3_74(what, x, y, ...) what(x, y) EXPAND(FOREACH3_73(what, x, __VA_ARGS__))
#define FOREACH3_75(what, x, y, ...) what(x, y) EXPAND(FOREACH3_74(what, x, __VA_ARGS__))
#define FOREACH3_76(what, x, y, ...) what(x, y) EXPAND(FOREACH3_75(what, x, __VA_ARGS__))
#define FOREACH3_77(what, x, y, ...) what(x, y) EXPAND(FOREACH3_76(what, x, __VA_ARGS__))
#define FOREACH3_78(what, x, y, ...) what(x, y) EXPAND(FOREACH3_77(what, x, __VA_ARGS__))
#define FOREACH3_79(what, x, y, ...) what(x, y) EXPAND(FOREACH3_78(what, x, __VA_ARGS__))
#define FOREACH3_80(what, x, y, ...) what(x, y) EXPAND(FOREACH3_79(what, x, __VA_ARGS__))
#define FOREACH3_81(what, x, y, ...) what(x, y) EXPAND(FOREACH3_80(what, x, __VA_ARGS__))
#define FOREACH3_82(what, x, y, ...) what(x, y) EXPAND(FOREACH3_81(what, x, __VA_ARGS__))
#define FOREACH3_83(what, x, y, ...) what(x, y) EXPAND(FOREACH3_82(what, x, __VA_ARGS__))
#define FOREACH3_84(what, x, y, ...) what(x, y) EXPAND(FOREACH3_83(what, x, __VA_ARGS__))
#define FOREACH3_85(what, x, y, ...) what(x, y) EXPAND(FOREACH3_84(what, x, __VA_ARGS__))
#define FOREACH3_86(what, x, y, ...) what(x, y) EXPAND(FOREACH3_85(what, x, __VA_ARGS__))
#define FOREACH3_87(what, x, y, ...) what(x, y) EXPAND(FOREACH3_86(what, x, __VA_ARGS__))
#define FOREACH3_88(what, x, y, ...) what(x, y) EXPAND(FOREACH3_87(what, x, __VA_ARGS__))
#define FOREACH3_89(what, x, y, ...) what(x, y) EXPAND(FOREACH3_88(what, x, __VA_ARGS__))
#define FOREACH3_90(what, x, y, ...) what(x, y) EXPAND(FOREACH3_89(what, x, __VA_ARGS__))
#define FOREACH3_91(what, x, y, ...) what(x, y) EXPAND(FOREACH3_90(what, x, __VA_ARGS__))
#define FOREACH3_92(what, x, y, ...) what(x, y) EXPAND(FOREACH3_91(what, x, __VA_ARGS__))
#define FOREACH3_93(what, x, y, ...) what(x, y) EXPAND(FOREACH3_92(what, x, __VA_ARGS__))
#define FOREACH3_94(what, x, y, ...) what(x, y) EXPAND(FOREACH3_93(what, x, __VA_ARGS__))
#define FOREACH3_95(what, x, y, ...) what(x, y) EXPAND(FOREACH3_94(what, x, __VA_ARGS__))
#define FOREACH3_96(what, x, y, ...) what(x, y) EXPAND(FOREACH3_95(what, x, __VA_ARGS__))
#define FOREACH3_97(what, x, y, ...) what(x, y) EXPAND(FOREACH3_96(what, x, __VA_ARGS__))
#define FOREACH3_98(what, x, y, ...) what(x, y) EXPAND(FOREACH3_97(what, x, __VA_ARGS__))
#define FOREACH3_99(what, x, y, ...) what(x, y) EXPAND(FOREACH3_98(what, x, __VA_ARGS__))



#define FOREACH_NARG(...) FOREACH_NARG_(__VA_ARGS__, FOREACH_RSEQ_N())

#define FOREACH_NARG_(...) EXPAND(FOREACH_ARG_N(__VA_ARGS__))

#define FOREACH_ARG_N( _99, _98, _97, _96, _95, _94, _93, _92, _91, _90, _89, _88, _87, _86, _85, _84, _83, _82, _81, _80, _79, _78, _77, _76, _75, _74, _73, _72, _71, _70, _69, _68, _67, _66, _65, _64, _63, _62, _61, _60, _59, _58, _57, _56, _55, _54, _53, _52, _51, _50, _49, _48, _47, _46, _45, _44, _43, _42, _41, _40, _39, _38, _37, _36, _35, _34, _33, _32, _31, _30, _29, _28, _27, _26, _25, _24, _23, _22, _21, _20, _19, _18, _17, _16, _15, _14, _13, _12, _11, _10, _9, _8, _7, _6, _5, _4, _3, _2, _1, N, ...) N

#define FOREACH_RSEQ_N() 99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,  87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,  74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,  61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,  48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,  9,  8,  7,  6,  5,  4,  3,  2,  1, 0

#define CONCATENATE(x,y) x##y

#define FOREACH_(N, what, ...) EXPAND(CONCATENATE(FOREACH_, N)(what, __VA_ARGS__))
#define FOREACH2_(N, what, ...) EXPAND(CONCATENATE(FOREACH2_, N)(what, __VA_ARGS__))
#define FOREACH3_(N, what, x, ...) EXPAND(CONCATENATE(FOREACH3_, N)(what, x, __VA_ARGS__))

#define FOREACH(what, ...) FOREACH_(FOREACH_NARG(__VA_ARGS__), what, __VA_ARGS__)
#define FOREACH2(what, ...) FOREACH2_(FOREACH2_NARG(__VA_ARGS__), what, __VA_ARGS__)
#define FOREACH3(what, x, ...) FOREACH3_(FOREACH_NARG(__VA_ARGS__), what, x, __VA_ARGS__)


#define LOAD(name) assign(v.Get(#name), name);
#define LOAD_IF_HAS(name) { if (v.Contains(#name)) assign(v.Get(#name), name); }
#define LOAD_VV(name) assign(v.Get(#name), vv.name);
#define LOAD_IF_HAS_VV(name) { if (v.Contains(#name)) assign(v.Get(#name), vv.name); }
#define SAVE(name) assign(name, v[#name]);
#define SAVE_VV(name) assign(vv.name, v[#name]);

#define SAVE_ALL(...) { FOREACH(SAVE, __VA_ARGS__) }
#define LOAD_ALL(...) { FOREACH(LOAD, __VA_ARGS__) }
#define LOAD_ALL_IF_HAS(...) { FOREACH(LOAD_IF_HAS, __VA_ARGS__) }

#define LOAD_ALL_VV(to, ...) { auto& vv = to; FOREACH(LOAD_VV, __VA_ARGS__) }
#define SAVE_ALL_VV(from, ...) { const auto& vv = from; FOREACH(SAVE_VV, __VA_ARGS__) }

#define LOAD_ALL_IF_HAS_VV(to, ...) { auto& vv = to; FOREACH(LOAD_ALL_IF_HAS, __VA_ARGS__) }



#endif
